# Generated by Django 4.2.20 on 2025-05-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('date_posted', models.DateField()),
                ('product_or_service', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=100)),
                ('sal', models.CharField(max_length=100)),
                ('basic_qualification', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_roles', models.TextField()),
                ('about_role', models.TextField()),
                ('requirements', models.TextField()),
                ('nice_to_have', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField()),
                ('department', models.CharField(max_length=255)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='PiDot.activerole', to_field='job_id')),
            ],
        ),
    ]
