# Generated by Django 4.2.20 on 2025-05-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PiDot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='department',
            new_name='team',
        ),
        migrations.AddField(
            model_name='activerole',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
